# Purpose
This code book lists the variables contained within tidy.txt

# Factors
* Subject - the ID of the individual subject
* Activity - what activity was performed during measurements

# Measurements
"tBodyAccMeanX"            
"tBodyAccMeanY"           
"tBodyAccMeanZ"         
"tBodyAccStdX"          
"tBodyAccStdY"           
"tBodyAccStdZ"            
"tGravityAccMeanX"       
"tGravityAccMeanY"       
"tGravityAccMeanZ"       
"tGravityAccStdX"         
"tGravityAccStdY"       
"tGravityAccStdZ"        
"tBodyAccJerkMeanX"      
"tBodyAccJerkMeanY"       
"tBodyAccJerkMeanZ"      
"tBodyAccJerkStdX"       
"tBodyAccJerkStdY"       
"tBodyAccJerkStdZ"        
"tBodyGyroMeanX"         
"tBodyGyroMeanY"         
"tBodyGyroMeanZ"         
"tBodyGyroStdX"           
"tBodyGyroStdY"          
"tBodyGyroStdZ"          
"tBodyGyroJerkMeanX"     
"tBodyGyroJerkMeanY"      
"tBodyGyroJerkMeanZ"     
"tBodyGyroJerkStdX"       
"tBodyGyroJerkStdY"      
"tBodyGyroJerkStdZ"       
"tBodyAccMagMean"        
"tGravityAccMagMean"     
"tBodyAccJerkMagMean"    
"tBodyGyroMagMean"        
"tBodyGyroJerkMagMean"   
"fBodyAccMeanX"          
"fBodyAccMeanY"           
"fBodyAccMeanZ"           
"fBodyAccStdX"            
"fBodyAccStdY"           
"fBodyAccStdZ"            
"fBodyAccJerkMeanX"       
"fBodyAccJerkMeanY"       
"fBodyAccJerkMeanZ"       
"fBodyAccJerkStdX"        
"fBodyAccJerkStdY"        
"fBodyAccJerkStdZ"        
"fBodyGyroMeanX"          
"fBodyGyroMeanY"         
"fBodyGyroMeanZ"          
"fBodyGyroStdX"           
"fBodyGyroStdY"           
"fBodyGyroStdZ"           
"fBodyAccMagMean"         
"fBodyBodyAccJerkMagMean"  
"fBodyBodyGyroMagMean"    
"fBodyBodyGyroJerkMagMean"

## Activities
*WALKING
*WALKING_UPSTAIRS
*WALKING_DOWNSTAIRS
*SITTING
*STANDING
*LAYING